### PR TITLE
Updated README to reflect project ownership

### PR DESCRIPTION
**Pull request by kurtfunai**
# Preview of changes
# TweetCity
### Property of

logo-colour
## Usage

Change the keys in config.exs or set the appropriate environment variables:

``` bash
    env consumer_secret="xxxx" \
        consumer_key="xxxx"  \
        oauth_token="xxxx" \
        oauth_token_secret="xxxx" \
        iex -S mix
```

Then in `iex`

``` iex
TweetCity.Stream.start_link
```

&copy; Fullscript

### CODE REVIEW

**Comment by uri** [comment]
lol you god damn trolls

**Comment by patvice** [comment]
:trollface:

**Comment by celsodantas** [comment]
lol

🚢

**Comment by kurtfunai** [comment]
You ate the "free" pizza but didn't read the agreement. 🍕 💀

**Comment by celsodantas** [comment]
not going to merge?

**Comment by kurtfunai** [comment]
lol <3

**Pull request closed without merging**
